# Generated by Django 2.0.5 on 2018-08-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='pais',
            new_name='ciudad',
        ),
    ]
