# Generated by Django 2.0.5 on 2018-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_auto_20180803_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
